# Generated by Django 4.2 on 2024-04-04 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('element_name', models.CharField(max_length=250, verbose_name='Element Name')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('type', models.CharField(max_length=250, verbose_name='Type')),
                ('location_name', models.CharField(max_length=250, verbose_name='Location Name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('point_type', models.CharField(max_length=250, verbose_name='Point Type')),
                ('point_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Point Name')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='geoconnector.location')),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('resource_link_name', models.CharField(max_length=250, verbose_name='Resource Link Name')),
            ],
            options={
                'verbose_name': 'Resource Link',
                'verbose_name_plural': 'Resource Links',
            },
        ),
        migrations.CreateModel(
            name='PointResourceLinkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=20)),
                ('resource_links', models.ManyToManyField(related_name='point_statuses', to='geoconnector.resourcelink')),
            ],
            options={
                'verbose_name': 'Point Resource Link Status',
                'verbose_name_plural': 'Point Resource Link Statuses',
            },
        ),
        migrations.CreateModel(
            name='PointElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_elements', to='geoconnector.element')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_elements', to='geoconnector.point')),
            ],
            options={
                'verbose_name': 'Point Element',
                'verbose_name_plural': 'Point Elements',
            },
        ),
    ]
