# Generated by Django 4.2 on 2024-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoconnector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointresourcelinkstatus',
            name='points',
            field=models.ManyToManyField(related_name='points', to='geoconnector.point'),
        ),
    ]
